theme: jekyll-theme-architect
pagination:
  enabled: true
  debug: false
  per_page: 10
  permalink: '/blog/page:num/'
  collection: 'posts' 
plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache
 - jekyll-paginate-v2
bcolor: "#ddd"
excerpt_separator: <!--more-->
title: Silvercircle's Jekyll playground
description: A Jekyll test site with no particular purpose.
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
site-verification: PLmE9YXaD6lmJOTH9qkv5IOOLivAP0xS8SfwYhK1Blo
timezone: Europe/Berlin
have_disqus: true
disqus_registered_baseurl: https://miranda.or.at