theme: jekyll-theme-architect
paginate: 10
plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache
 - jekyll-paginate
 - jekyll-textile-convert 