theme: jekyll-theme-architect
paginate: 10
plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache
 - jekyll-paginate
bcolor: "#ddd"
excerpt_separator: <!--more-->
title: Silvercircle's Jekyll playground
description: A Jekyll test site with no particular purpose.
